version: '3.3'
services:
  feishu-chatgpt:
    container_name: feishu-openai
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      APP_ID: cli_axxx
      APP_SECRET: xxx
      APP_ENCRYPT_KEY: xxx
      APP_VERIFICATION_TOKEN: xxx
      OPENAI_KEY: sk-xxx,sk-xxx,sk-xxx
      HTTP_PORT: 9000
