#  飞书
BASE_URL: https://open.feishu.cn
APP_ID: cli_axxx
APP_SECRET: xxx
APP_ENCRYPT_KEY: xxx
APP_VERIFICATION_TOKEN: xxx
# 请确保和飞书应用管理平台中的设置一致
BOT_NAME: chatGpt
# openAI key 支持负载均衡 可以填写多个key 用逗号分隔
OPENAI_KEY: sk-xxx,sk-xxx,sk-xxx
# openAI model 指定模型，默认为 gpt-3.5-turbo
# 可选参数有："gpt-4-0314", "gpt-4", "gpt-3.5-turbo-0301","gpt-3.5-turbo-16k", "gpt-3.5-turbo"，如果使用gpt-4，请确认自己是否有接口调用白名单
OPENAI_MODEL: gpt-4
# openAI 最大token数 默认为2000
OPENAI_MAX_TOKENS: 2000
# 响应超时时间，单位为毫秒，默认为550毫秒
OPENAI_HTTP_CLIENT_TIMEOUT: 550
# 服务器配置
HTTP_PORT: 9000
HTTPS_PORT: 9001
USE_HTTPS: false
CERT_FILE: cert.pem
KEY_FILE: key.pem
# openai 地址, 一般不需要修改, 除非你有自己的反向代理
API_URL: https://api.openai.com
# 代理设置, 例如 "http://127.0.0.1:7890", ""代表不使用代理
HTTP_PROXY: ""
# 是否开启流式接口返回
STREAM_MODE: false # set true to use stream mode